# One command to bump the app version across every file that carries it.
#
#   scripts\bump-version.ps1 0.5.0
#
# Single source of truth is pyproject.toml; the other carriers are mirrors
# this script keeps in step:
#   installer/mortgage-work.iss  fallback macro (build.ps1/CI inject /D)
#   frontend/package.json        cosmetic, shows in npm's run banner
#   uv.lock / package-lock.json  regenerated by uv / npm themselves

param(
    [Parameter(Position = 0, Mandatory = $true)][string]$Version
)

$ErrorActionPreference = "Stop"
Set-Location (Join-Path $PSScriptRoot "..")

$Version = $Version.TrimStart("v")
if ($Version -notmatch '^\d+(\.\d+)*([-.][0-9A-Za-z.]+)?$') {
    throw "version must look like 1.2.3 (got '$Version')"
}

# Byte-faithful patching: Set-Content rewrites line endings and PS 5.1's
# -Encoding UTF8 adds a BOM that tomllib refuses, so go through System.IO
# with BOM-less UTF-8 instead. Only the first match per file is touched.
$Utf8NoBom = New-Object System.Text.UTF8Encoding($false)
function Patch-VersionIn([string]$Path, [string]$Pattern) {
    $full = Join-Path (Get-Location) $Path
    $text = [System.IO.File]::ReadAllText($full)
    $rx = New-Object System.Text.RegularExpressions.Regex $Pattern
    if (-not $rx.IsMatch($text)) { throw "version pattern not found in $Path" }
    $repl = "`${1}" + $Version + "`${2}"
    [System.IO.File]::WriteAllText($full, $rx.Replace($text, $repl, 1), $Utf8NoBom)
    Write-Host "  patched $Path"
}

Write-Host "> bumping version to $Version"
Patch-VersionIn "pyproject.toml" '(?m)^(version = ")[^"]+(")'
Patch-VersionIn "installer\mortgage-work.iss" '(#define MyAppVersion ")[^"]+(")'
Patch-VersionIn "frontend\package.json" '("version": ")[^"]+(")'

Write-Host "> regenerating uv.lock..."
uv lock

Write-Host "> regenerating frontend/package-lock.json..."
Push-Location frontend
try {
    npm install --package-lock-only --no-audit --no-fund
}
finally {
    Pop-Location
}

Write-Host ""
Write-Host "done - version is $Version everywhere (run .\build.ps1 to package)"
