/* ================= Viewer documents (static mock content) =================
   Injected via v-html; inline onclick handlers resolve to window globals
   registered in bridge.js (same contract as the pre-Vue single-file page). */
import { MODEL_CATALOG, PROVIDERS, providerItemsHtml, modelItemsHtml } from "./catalog.js";
import { effectiveCitizenship } from "./clients.js";
import { AGENT_DOCS } from "./agent.js";

export const DOCS = {
  ...AGENT_DOCS,
  profile: {
    label: "PROFILE.md", badge: "md", crumb: ["sarah-mitchell", "PROFILE.md"],
    html: `<div class="md-doc">
      <h1>Sarah Mitchell <span class="stage docs">Collecting Docs</span></h1>
      <h2>Contact</h2>
      <div class="kv">
        <div class="k">Phone</div><div class="v">(949) 555-0182 · <span class="dim">prefers text</span></div>
        <div class="k">Email</div><div class="v">sarah.m@gmail.com</div>
      </div>
      <h2>Loan</h2>
      <div class="kv">
        <div class="k">Purpose</div><div class="v"><b>Purchase</b> · Irvine, CA · primary residence</div>
        <div class="k">Target</div><div class="v"><b>$680,000</b> · 20% down · LTV 80%</div>
        <div class="k">Product</div><div class="v">TBD — comparing <b>conventional</b> vs <b>bank-statement</b> (self-employed)</div>
        <div class="k">Co-borrower</div><div class="v">David Mitchell · W-2 · $8,200/mo base</div>
      </div>
      <h2>Milestones</h2>
      <div class="kv">
        <div class="k">Pre-qual sent</div><div class="v">Jul 21</div>
        <div class="k">Docs requested</div><div class="v">Jul 22 · <span class="bad">3 still missing</span></div>
        <div class="k">Target close</div><div class="v"><b>Sep 15</b></div>
      </div>
      <h2>Notes</h2>
      <p>Self-employed 2 yrs (S-corp, marketing agency). Wants to move fast — house is in escrow backup position. Check bank-statement program if conventional DTI is tight.</p>
      <div class="ai-note"><span class="who">AI</span> · This file is maintained from documents in this folder. Edited by you 2h ago; last auto-update after <b>boa-statement-jul.pdf</b> was added.</div>
    </div>`,
  },
  paystub: {
    label: "paystub-2026-07.pdf", badge: "pdf", crumb: ["sarah-mitchell", "income", "paystub-2026-07.pdf"],
    html: `<div class="pdf-wrap">
      <div class="pdf-chrome"><span>PDF · Page 1 / 1 · 100%</span><span>Extracted ✓ · gross $4,100.00 semi-monthly</span></div>
      <div class="pdf-page">
        <div class="ph-head"><b>ACME DESIGN CO.</b><span>EARNINGS STATEMENT</span></div>
        <table>
          <tr><th>EMPLOYEE</th><th>PERIOD</th><th>PAY DATE</th></tr>
          <tr><td>MITCHELL, DAVID</td><td>07/01/2026 – 07/15/2026</td><td>07/18/2026</td></tr>
        </table>
        <table>
          <tr><th>EARNINGS</th><th>RATE</th><th>HOURS</th><th>CURRENT</th><th>YTD</th></tr>
          <tr><td>Regular</td><td>51.25</td><td>80.00</td><td>4,100.00</td><td>53,300.00</td></tr>
          <tr><td>Bonus</td><td>—</td><td>—</td><td>0.00</td><td>2,500.00</td></tr>
          <tr class="sum"><td>GROSS PAY</td><td></td><td></td><td>4,100.00</td><td>55,800.00</td></tr>
        </table>
        <table>
          <tr><th>DEDUCTIONS</th><th></th><th></th><th>CURRENT</th><th>YTD</th></tr>
          <tr><td>Federal Tax</td><td></td><td></td><td>492.00</td><td>6,396.00</td></tr>
          <tr><td>401(k)</td><td></td><td></td><td>246.00</td><td>3,198.00</td></tr>
          <tr class="sum"><td>NET PAY</td><td></td><td></td><td>3,362.00</td><td>—</td></tr>
        </table>
        <div class="fine">This is a demo document generated for UI mock purposes only. Not a real earnings statement.</div>
      </div>
    </div>`,
  },
  missing: {
    label: "missing-docs.ai", badge: "ai", crumb: ["sarah-mitchell", "ai", "missing-docs.ai"],
    html: `<div class="md-doc">
      <h1>Missing Documents <span class="stage docs">3 OPEN</span></h1>
      <p class="dim" style="font:400 11px var(--mono)">Generated by AI · Jul 28, 10:42 AM · from folder contents vs. checklist for self-employed purchase</p>
      <h2>Income — Sarah (self-employed)</h2>
      <div class="checklist">
        <div class="check done"><span class="box">✓</span> 12-mo business bank statements (10 of 12)</div>
        <div class="check"><span class="box"></span> Bank statements — Apr &amp; May 2026 <span class="tag-req need">NEEDED</span></div>
        <div class="check"><span class="box"></span> CPA letter — 2 yrs self-employment <span class="tag-req need">NEEDED</span></div>
      </div>
      <h2>Income — David (W-2)</h2>
      <div class="checklist">
        <div class="check done"><span class="box">✓</span> Paystubs (Jun, Jul)</div>
        <div class="check done"><span class="box">✓</span> W-2 2025</div>
        <div class="check"><span class="box"></span> W-2 2024 <span class="tag-req wait">REQUESTED 07/22</span></div>
      </div>
      <h2>Assets &amp; Credit</h2>
      <div class="checklist">
        <div class="check done"><span class="box">✓</span> BofA statements (Jun, Jul)</div>
        <div class="check done"><span class="box">✓</span> Credit report (softpull 07/21 · 742 mid)</div>
      </div>
      <div class="ai-note"><span class="who">AI</span> · Draft email requesting the 3 missing items is ready → <b>ai/request-email-draft.ai</b></div>
    </div>`,
  },
  income: {
    label: "income-analysis.ai", badge: "ai", crumb: ["sarah-mitchell", "ai", "income-analysis.ai"],
    html: `<div class="md-doc">
      <h1>Income Analysis <span class="stage active">DRAFT</span></h1>
      <p class="dim" style="font:400 11px var(--mono)">Generated by AI · Jul 28, 10:47 AM · sources: 6 files in income/ and assets/</p>
      <h2>Qualifying Income</h2>
      <table class="mtable">
        <tr><th>Borrower</th><th>Method</th><th>Basis</th><th>Monthly</th></tr>
        <tr><td>David (W-2)</td><td>Base salary</td><td>Paystub YTD ✓ matches W-2 2025</td><td>$8,200</td></tr>
        <tr><td>Sarah (self-emp)</td><td>12-mo bank stmt</td><td>Avg deposits $23,400 × 50% expense factor</td><td>$11,700</td></tr>
        <tr class="total"><td colspan="3">Total qualifying income</td><td>$19,900</td></tr>
      </table>
      <h2>Ratios @ $680,000 · 20% down · 6.625% / 30yr</h2>
      <table class="mtable">
        <tr><th>Item</th><th>Monthly</th><th>Ratio</th><th>Check</th></tr>
        <tr><td>PITI (est. w/ tax+ins)</td><td>$4,381</td><td>22.0% front</td><td><span class="ok">OK</span></td></tr>
        <tr><td>Total obligations</td><td>$6,140</td><td>30.9% back</td><td><span class="ok">OK — under 43%</span></td></tr>
      </table>
      <h2>Flags</h2>
      <table class="mtable">
        <tr><td><span class="bad">▲</span> Apr &amp; May statements missing</td><td colspan="3">12-mo average currently uses 10 months — number may move</td></tr>
        <tr><td><span class="bad">▲</span> Large deposit $18,000 on 06/14</td><td colspan="3">Will need LOE + source if conventional; OK under A&amp;D bank-stmt program</td></tr>
      </table>
      <div class="ai-note"><span class="who">AI</span> · Cross-checked against <b>products/A&amp;D Mortgage/non-qm-bank-statement.pdf</b>: qualifies at 80% LTV, min FICO 680 (has 742). Conventional also viable if LOE clears the 06/14 deposit.</div>
    </div>`,
  },
  guideline: {
    label: "non-qm-bank-statement.pdf", badge: "pdf", crumb: ["products", "A&D Mortgage", "non-qm-bank-statement.pdf"],
    html: `<div class="pdf-wrap">
      <div class="pdf-chrome"><span>PDF · Page 3 / 24 · 100%</span><span>Indexed ✓ · searchable by AI</span></div>
      <div class="pdf-page">
        <div class="ph-head"><b>A&amp;D MORTGAGE — BANK STATEMENT PROGRAM</b><span>EFF. 07/2026</span></div>
        <table>
          <tr><th>DOC TYPE</th><th>MAX LTV</th><th>MIN FICO</th><th>MAX DTI</th><th>LOAN AMOUNT</th></tr>
          <tr><td>12-mo Personal</td><td>80%</td><td>660</td><td>50%</td><td>≤ $1.5M</td></tr>
          <tr><td>12-mo Business</td><td>80%</td><td>680</td><td>50%</td><td>≤ $2.0M</td></tr>
          <tr><td>24-mo Business</td><td>85%</td><td>700</td><td>50%</td><td>≤ $3.0M</td></tr>
        </table>
        <table>
          <tr><th>EXPENSE FACTOR</th><th></th></tr>
          <tr><td>Service business, no CPA letter</td><td>50%</td></tr>
          <tr><td>With CPA/EA expense letter</td><td>As stated, min 20%</td></tr>
        </table>
        <div class="fine">Demo content for UI mock purposes only. Not actual lender guidelines.</div>
      </div>
    </div>`,
  },
  models: {
    label: "models.yaml", badge: "yml", crumb: ["settings", "models.yaml"],
    html: `<div class="md-doc">
      <h1>Models &amp; Providers <button class="btn-sm primary" style="margin-left:auto" onclick="toggleAddModel()">Add Model</button></h1>
      <p class="dim" style="font:400 11px var(--mono)">Plain file at ~/MortgageWork/settings/models.yaml · edit here or in any editor</p>
      <div id="add-form" class="add-form hidden">
        <div><label>Provider</label>
          <div class="dd">
            <button class="dd-btn" onclick="ddToggle(this, event)"><span id="nm-provider">${PROVIDERS[0]}</span><span class="arr">▼</span></button>
            <div id="nm-provider-menu" class="dd-menu hidden">${providerItemsHtml()}</div>
          </div>
        </div>
        <div><label>Models</label>
          <div class="dd">
            <button class="dd-btn" onclick="ddToggle(this, event)"><span id="nm-model">${MODEL_CATALOG[PROVIDERS[0]].models[0]}</span><span class="arr">▼</span></button>
            <div id="nm-model-menu" class="dd-menu hidden">${modelItemsHtml(PROVIDERS[0])}</div>
          </div>
        </div>
        <div><label>Base URL</label><input id="nm-url" value="${MODEL_CATALOG[PROVIDERS[0]].url}"></div>
        <div><label>API Key</label><input id="nm-key" type="password" placeholder="sk-…"></div>
        <div class="apply-row full"><button class="btn-sm primary" onclick="saveNewModel()">Save</button><button class="btn-sm" onclick="toggleAddModel()">Cancel</button></div>
      </div>
      <h2>Providers</h2>
      <div id="prov-list">
        <div class="prov">
          <div class="prov-head">
            <span class="pname">OpenAI</span>
            <span class="pstatus ok">● CONNECTED</span>
            <span class="pchecked">checked 2h ago</span>
            <span class="pactions"><button class="btn-sm" onclick="provCheck(this)">Check</button><button class="btn-sm" onclick="provRemove(this, 'OpenAI')">Remove</button></span>
          </div>
          <div class="prov-body">
            <div class="pkey">sk-••••••••7f2a</div>
            <div class="mrow on"><span class="mname">gpt-4o</span><span class="dlbl">DEFAULT</span><span class="m-acts"><button class="btn-sm" onclick="toggleModelDisable(this, 'gpt-4o')">Disable</button><button class="btn-sm" onclick="removeModel(this, 'gpt-4o')">Remove</button></span><span class="msw on" onclick="setDefaultModel(this, 'gpt-4o')"></span></div>
            <div class="mrow"><span class="mname">gpt-4o-mini</span><span class="dlbl">DEFAULT</span><span class="m-acts"><button class="btn-sm" onclick="toggleModelDisable(this, 'gpt-4o-mini')">Disable</button><button class="btn-sm" onclick="removeModel(this, 'gpt-4o-mini')">Remove</button></span><span class="msw" onclick="setDefaultModel(this, 'gpt-4o-mini')"></span></div>
          </div>
        </div>
        <div class="prov">
          <div class="prov-head">
            <span class="pname">Anthropic</span>
            <span class="pstatus ok">● CONNECTED</span>
            <span class="pchecked">checked yesterday</span>
            <span class="pactions"><button class="btn-sm" onclick="provCheck(this)">Check</button><button class="btn-sm" onclick="provRemove(this, 'Anthropic')">Remove</button></span>
          </div>
          <div class="prov-body">
            <div class="pkey">sk-ant-••••41c9</div>
            <div class="mrow"><span class="mname">claude-sonnet</span><span class="dlbl">DEFAULT</span><span class="m-acts"><button class="btn-sm" onclick="toggleModelDisable(this, 'claude-sonnet')">Disable</button><button class="btn-sm" onclick="removeModel(this, 'claude-sonnet')">Remove</button></span><span class="msw" onclick="setDefaultModel(this, 'claude-sonnet')"></span></div>
          </div>
        </div>
      </div>
    </div>`,
  },
};

/* Scaffolded PROFILE.md for a freshly created client — the client IS this file */
export function freshProfileDoc(slug, name, phone, email, purpose, amount, citizenship, co) {
  // Citizenship is per-borrower; with a co-borrower the effective status is the most restrictive
  const citRows = co
    ? `<div class="k">Borrower</div><div class="v">${name} · ${citizenship}</div>
        <div class="k">Co-Borrower</div><div class="v">${co.name} · ${co.citizenship}</div>
        <div class="k">Citizenship</div><div class="v">${effectiveCitizenship([citizenship, co.citizenship])} <span class="dim">— most restrictive of 2 borrowers</span></div>`
    : `<div class="k">Citizenship</div><div class="v">${citizenship}</div>`;
  return {
    label: "PROFILE.md", badge: "md", crumb: [slug, "PROFILE.md"],
    html: `<div class="md-doc">
      <h1>${name} <span class="stage lead">NEW LEAD</span></h1>
      <p class="dim" style="font:400 11px var(--mono)">Scaffolded just now · fills itself as documents arrive</p>
      <h2>Contact</h2>
      <div class="kv">
        <div class="k">Phone</div><div class="v">${phone || '<span class="dim">—</span>'}</div>
        <div class="k">Email</div><div class="v">${email || '<span class="dim">—</span>'}</div>
      </div>
      <h2>Loan</h2>
      <div class="kv">
        <div class="k">Purpose</div><div class="v">${purpose}</div>
        <div class="k">Target</div><div class="v">${amount}</div>
        ${citRows}
        <div class="k">Income</div><div class="v"><span class="dim">— waiting on docs</span></div>
        <div class="k">Credit</div><div class="v"><span class="dim">— waiting on pull</span></div>
      </div>
      <p class="dim" style="font:400 11px var(--mono)">Drop documents into this folder — extraction fills this file automatically.</p>
    </div>`,
  };
}
