/* ================= Viewer documents (static mock content) =================
   Injected via v-html; inline onclick handlers resolve to window globals
   registered in bridge.js (same contract as the pre-Vue single-file page). */
import { AGENT_DOCS } from "./agent.js";

export const DOCS = {
  ...AGENT_DOCS,
  clientmeta: {
    label: "client.yaml", badge: "md", crumb: ["sarah-mitchell", "client.yaml"],
    html: `<div class="md-doc">
      <p class="dim" style="font:400 11px var(--mono)"># Machine-managed by Mortgage Work — do not edit by hand.</p>
      <h1>client.yaml</h1>
      <pre style="font:400 12px var(--mono); line-height:1.6">schema: 1
name: Sarah Mitchell
purpose: purchase
stage: lead
amount: 680000
contact:
  phone: "(949) 555-0182"
  email: "sarah.m@gmail.com"
borrowers:
  - name: Sarah Mitchell
    citizenship: us_citizen
  - name: David Mitchell
    citizenship: us_citizen
created: 2026-07-15</pre>
      <div class="ai-note"><span class="who">SYSTEM</span> · Structured facts from the New Client form. Free-form notes live in <b>ai/profile.ai</b>.</div>
    </div>`,
  },
  profile: {
    label: "profile.ai", badge: "ai", crumb: ["sarah-mitchell", "ai", "profile.ai"],
    html: `<div class="md-doc">
      <h1>Sarah Mitchell — clerk</h1>
      <p class="dim" style="font:400 11px var(--mono)">Maintained by clerk · as of aa70555 · 2026-07-28</p>
      <h2>Loan</h2>
      <div class="kv">
        <div class="k">Purpose</div><div class="v">Purchase · Irvine, CA · primary residence</div>
        <div class="k">Target</div><div class="v">$680,000 · 20% down · LTV 80%</div>
        <div class="k">Product</div><div class="v">TBD — comparing conventional vs bank-statement (self-employed)</div>
      </div>
      <h2>Borrowers</h2>
      <div class="kv">
        <div class="k">Primary</div><div class="v">Sarah Mitchell · US citizen · self-employed 2 yrs (S-corp)</div>
        <div class="k">Co-borrower</div><div class="v">David Mitchell · US citizen · W-2 · $8,200/mo base</div>
      </div>
      <h2>Documents on file</h2>
      <pre style="font:400 11px var(--mono); line-height:1.6">income/   paystub-2026-06.pdf, paystub-2026-07.pdf, w2-2025.pdf
assets/   boa-statement-jun.pdf, boa-statement-jul.pdf
credit/   credit-report.pdf (softpull 07/21 · mid 742)</pre>
      <h2>Open items</h2>
      <div class="checklist">
        <div class="check"><span class="box"></span> Bank statements — Apr &amp; May 2026 <span class="tag-req need">NEEDED</span></div>
        <div class="check"><span class="box"></span> CPA letter — 2 yrs self-employment <span class="tag-req need">NEEDED</span></div>
        <div class="check"><span class="box"></span> W-2 2024 (David) <span class="tag-req wait">REQUESTED 07/22</span></div>
      </div>
      <h2>Context</h2>
      <p>07/15 — Borrower wants to move fast; house is in escrow backup position. Check bank-statement program if conventional DTI is tight. Large deposit $18,000 on 06/14 will need LOE if conventional.</p>
    </div>`,
  },
  paystub: {
    label: "paystub-2026-07.pdf", badge: "pdf", crumb: ["sarah-mitchell", "income", "paystub-2026-07.pdf"],
    html: `<div class="pdf-wrap">
      <div class="pdf-chrome"><span>PDF · Page 1 / 1 · 100%</span><span>Extracted ✓ · gross $4,100.00 semi-monthly</span></div>
      <div class="pdf-page">
        <div class="ph-head"><b>ACME DESIGN CO.</b><span>EARNINGS STATEMENT</span></div>
        <table>
          <tr><th>EMPLOYEE</th><th>PERIOD</th><th>PAY DATE</th></tr>
          <tr><td>MITCHELL, DAVID</td><td>07/01/2026 – 07/15/2026</td><td>07/18/2026</td></tr>
        </table>
        <table>
          <tr><th>EARNINGS</th><th>RATE</th><th>HOURS</th><th>CURRENT</th><th>YTD</th></tr>
          <tr><td>Regular</td><td>51.25</td><td>80.00</td><td>4,100.00</td><td>53,300.00</td></tr>
          <tr><td>Bonus</td><td>—</td><td>—</td><td>0.00</td><td>2,500.00</td></tr>
          <tr class="sum"><td>GROSS PAY</td><td></td><td></td><td>4,100.00</td><td>55,800.00</td></tr>
        </table>
        <table>
          <tr><th>DEDUCTIONS</th><th></th><th></th><th>CURRENT</th><th>YTD</th></tr>
          <tr><td>Federal Tax</td><td></td><td></td><td>492.00</td><td>6,396.00</td></tr>
          <tr><td>401(k)</td><td></td><td></td><td>246.00</td><td>3,198.00</td></tr>
          <tr class="sum"><td>NET PAY</td><td></td><td></td><td>3,362.00</td><td>—</td></tr>
        </table>
        <div class="fine">This is a demo document generated for UI mock purposes only. Not a real earnings statement.</div>
      </div>
    </div>`,
  },
  missing: {
    label: "missing-docs.ai", badge: "ai", crumb: ["sarah-mitchell", "ai", "missing-docs.ai"],
    html: `<div class="md-doc">
      <h1>Missing Documents <span class="stage docs">3 OPEN</span></h1>
      <p class="dim" style="font:400 11px var(--mono)">Generated by AI · Jul 28, 10:42 AM · from folder contents vs. checklist for self-employed purchase</p>
      <h2>Income — Sarah (self-employed)</h2>
      <div class="checklist">
        <div class="check done"><span class="box">✓</span> 12-mo business bank statements (10 of 12)</div>
        <div class="check"><span class="box"></span> Bank statements — Apr &amp; May 2026 <span class="tag-req need">NEEDED</span></div>
        <div class="check"><span class="box"></span> CPA letter — 2 yrs self-employment <span class="tag-req need">NEEDED</span></div>
      </div>
      <h2>Income — David (W-2)</h2>
      <div class="checklist">
        <div class="check done"><span class="box">✓</span> Paystubs (Jun, Jul)</div>
        <div class="check done"><span class="box">✓</span> W-2 2025</div>
        <div class="check"><span class="box"></span> W-2 2024 <span class="tag-req wait">REQUESTED 07/22</span></div>
      </div>
      <h2>Assets &amp; Credit</h2>
      <div class="checklist">
        <div class="check done"><span class="box">✓</span> BofA statements (Jun, Jul)</div>
        <div class="check done"><span class="box">✓</span> Credit report (softpull 07/21 · 742 mid)</div>
      </div>
      <div class="ai-note"><span class="who">AI</span> · Draft email requesting the 3 missing items is ready → <b>ai/request-email-draft.ai</b></div>
    </div>`,
  },
  income: {
    label: "income-analysis.ai", badge: "ai", crumb: ["sarah-mitchell", "ai", "income-analysis.ai"],
    html: `<div class="md-doc">
      <h1>Income Analysis <span class="stage active">DRAFT</span></h1>
      <p class="dim" style="font:400 11px var(--mono)">Generated by AI · Jul 28, 10:47 AM · sources: 6 files in income/ and assets/</p>
      <h2>Qualifying Income</h2>
      <table class="mtable">
        <tr><th>Borrower</th><th>Method</th><th>Basis</th><th>Monthly</th></tr>
        <tr><td>David (W-2)</td><td>Base salary</td><td>Paystub YTD ✓ matches W-2 2025</td><td>$8,200</td></tr>
        <tr><td>Sarah (self-emp)</td><td>12-mo bank stmt</td><td>Avg deposits $23,400 × 50% expense factor</td><td>$11,700</td></tr>
        <tr class="total"><td colspan="3">Total qualifying income</td><td>$19,900</td></tr>
      </table>
      <h2>Ratios @ $680,000 · 20% down · 6.625% / 30yr</h2>
      <table class="mtable">
        <tr><th>Item</th><th>Monthly</th><th>Ratio</th><th>Check</th></tr>
        <tr><td>PITI (est. w/ tax+ins)</td><td>$4,381</td><td>22.0% front</td><td><span class="ok">OK</span></td></tr>
        <tr><td>Total obligations</td><td>$6,140</td><td>30.9% back</td><td><span class="ok">OK — under 43%</span></td></tr>
      </table>
      <h2>Flags</h2>
      <table class="mtable">
        <tr><td><span class="bad">▲</span> Apr &amp; May statements missing</td><td colspan="3">12-mo average currently uses 10 months — number may move</td></tr>
        <tr><td><span class="bad">▲</span> Large deposit $18,000 on 06/14</td><td colspan="3">Will need LOE + source if conventional; OK under A&amp;D bank-stmt program</td></tr>
      </table>
      <div class="ai-note"><span class="who">AI</span> · Cross-checked against <b>products/A&amp;D Mortgage/non-qm-bank-statement.pdf</b>: qualifies at 80% LTV, min FICO 680 (has 742). Conventional also viable if LOE clears the 06/14 deposit.</div>
    </div>`,
  },
  guideline: {
    label: "non-qm-bank-statement.pdf", badge: "pdf", crumb: ["products", "A&D Mortgage", "non-qm-bank-statement.pdf"],
    html: `<div class="pdf-wrap">
      <div class="pdf-chrome"><span>PDF · Page 3 / 24 · 100%</span><span>Indexed ✓ · searchable by AI</span></div>
      <div class="pdf-page">
        <div class="ph-head"><b>A&amp;D MORTGAGE — BANK STATEMENT PROGRAM</b><span>EFF. 07/2026</span></div>
        <table>
          <tr><th>DOC TYPE</th><th>MAX LTV</th><th>MIN FICO</th><th>MAX DTI</th><th>LOAN AMOUNT</th></tr>
          <tr><td>12-mo Personal</td><td>80%</td><td>660</td><td>50%</td><td>≤ $1.5M</td></tr>
          <tr><td>12-mo Business</td><td>80%</td><td>680</td><td>50%</td><td>≤ $2.0M</td></tr>
          <tr><td>24-mo Business</td><td>85%</td><td>700</td><td>50%</td><td>≤ $3.0M</td></tr>
        </table>
        <table>
          <tr><th>EXPENSE FACTOR</th><th></th></tr>
          <tr><td>Service business, no CPA letter</td><td>50%</td></tr>
          <tr><td>With CPA/EA expense letter</td><td>As stated, min 20%</td></tr>
        </table>
        <div class="fine">Demo content for UI mock purposes only. Not actual lender guidelines.</div>
      </div>
    </div>`,
  },
};
