<template>
  <section id="analysis" class="ai-section">
    <div class="shell">
      <div class="section-head">
        <p class="section-eyebrow"><span class="dot"></span> The AI reads the docs so you don't have to</p>
        <h2>Income analysis, condition checklists, written for you.</h2>
        <p>
          Drop paystubs, bank statements, and credit reports into a borrower folder.
          The AI reads them, calculates qualifying income, flags missing items, and
          cross-checks against lender guidelines — all saved next to the file.
        </p>
      </div>

      <div class="ai-grid">
        <!-- Left: income analysis (real content from frontend/src/mocks/docs.js) -->
        <div class="ai-card">
          <h3>Income Analysis</h3>
          <div class="card-meta">Generated by AI · 6 files in income/ and assets/ · Jul 28</div>
          <table class="income-table">
            <tbody>
            <tr><th>Borrower</th><th>Method</th><th>Monthly</th></tr>
            <tr><td>Co-borrower (W-2)</td><td>Base salary · YTD matches W-2</td><td>$8,200</td></tr>
            <tr><td>Sarah (self-emp)</td><td>12-mo bank stmt · 50% expense</td><td>$11,700</td></tr>
            <tr class="total"><td colspan="2">Total qualifying income</td><td>$19,900</td></tr>
            </tbody>
          </table>
          <div style="margin-top:14px">
            <div class="mock-flag"><span class="bad">▲</span> Apr &amp; May statements missing — 10 of 12 months used</div>
            <div class="mock-flag"><span class="bad">▲</span> Large deposit $18,000 on 06/14 — needs LOE if conventional</div>
            <div class="ai-note" style="margin-top:10px">
              <span class="who">AI</span> · Cross-checked against <b>A&amp;D Mortgage non-qm-bank-statement.pdf</b>:
              qualifies at 80% LTV, min FICO 680 (has 742).
            </div>
          </div>
        </div>

        <!-- Right: missing docs checklist (real content from frontend/src/mocks/docs.js) -->
        <div class="ai-card">
          <h3>Missing Documents <span class="stage docs">3 OPEN</span></h3>
          <div class="card-meta">Generated by AI · folder contents vs. self-employed purchase checklist</div>
          <div class="checklist">
            <div class="check done"><span class="box">✓</span> 12-mo business bank statements (10 of 12)</div>
            <div class="check"><span class="box"></span> Bank statements — Apr &amp; May 2026 <span class="tag-req need">NEEDED</span></div>
            <div class="check"><span class="box"></span> CPA letter — 2 yrs self-employment <span class="tag-req need">NEEDED</span></div>
            <div class="check done"><span class="box">✓</span> Paystubs (Jun, Jul)</div>
            <div class="check done"><span class="box">✓</span> W-2 2025</div>
            <div class="check"><span class="box"></span> W-2 2024 (co-borrower) <span class="tag-req wait">REQUESTED 07/22</span></div>
          </div>
          <div class="ai-note" style="margin-top:14px">
            <span class="who">AI</span> · Draft email requesting the 3 missing items is ready →
            <b>ai/request-email-draft.ai</b>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
